export const items = [
  {
    id: 1,
    name: 'Mindu IPA (500ml)',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-1048981_33790_sm.jpeg',
    brand: 'Mindu',
    price: 31.9,
    promo: 30.1,
  },
  {
    id: 2,
    name: 'Júpiter Apa (600ml)',
    brand: 'Júṕiter',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-45245_2897d_sm.jpeg',
    price: 31.9,
  },
  {
    id: 3,
    name: 'Júpiter Nebulosa (473ml)',
    brand: 'Júṕiter',
    url: 'https://untappd.akamaized.net/site/assets/images/temp/badge-beer-default.png',
    price: 31.9,
  },
  {
    id: 4,
    name: 'Júpiter 10 lúpulos (473ml)',
    brand: 'Júṕiter',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-1211106_266d3_sm.jpeg',
    price: 39.9,
  },
  {
    id: 5,
    name: 'Indie man (500ml)',
    brand: 'Indie',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-45245_2897d_sm.jpeg',
    price: 31.9,
    promo: 30.1,
  },
  {
    id: 6,
    name: 'Dogma sourmind maracujá (473ml)',
    brand: 'Dogma',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-45245_2897d_sm.jpeg',
    price: 39.9,
  },
  {
    id: 7,
    name: 'Dogma citra drop (473ml)',
    brand: 'Dogma',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-1048981_33790_sm.jpeg',
    price: 39.9,
    promo: 30.1,
  },
  {
    id: 8,
    name: 'Dogma Ed dorado (473ml)',
    brand: 'Dogma',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-45245_2897d_sm.jpeg',
    price: 39.9,
  },
  {
    id: 9,
    name: 'Perro Libre crowd 10 (473ml)',
    brand: 'Perro',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-702557_d2e0a_sm.jpeg',
    price: 39.9,
    promo: 30.1,
  },
  {
    id: 10,
    name: 'Invicta Boss (500ml)',
    brand: 'Invicta',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-45245_2897d_sm.jpeg',
    price: 31.9,
  },
  {
    id: 11,
    name: 'Invicta Damiana (500ml)',
    brand: 'Invicta',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-1048981_33790_sm.jpeg',
    price: 31.9,
    promo: 30.0,
  },
  {
    id: 12,
    name: 'Invicta Iniciação (500ml)',
    brand: 'Invicta',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-45245_2897d_sm.jpeg',
    price: 31.9,
  },
];
