export const items = [
  {
    id: 1,
    name: 'Mindu IPA (500ml)',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-1048981_33790_sm.jpeg',
    brand: 'Mindu',
    price: 31.9,
  },
  {
    id: 2,
    name: 'Munich Helles (500ml)',
    brand: '2 de Julho',
    url: 'https://untappd.akamaized.net/site/assets/images/temp/badge-beer-default.png',
    price: 31.9,
  },
  {
    id: 3,
    name: 'American IPA (500ml)',
    brand: '2 de Julho',
    url: 'https://untappd.akamaized.net/site/assets/images/temp/badge-beer-default.png',
    price: 31.9,
  },
  {
    id: 4,
    name: 'Júpiter Nebulosa (473ml)',
    brand: 'Júṕiter',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-2576863_3827f_sm.jpeg',
    price: 39.9,
  },
  {
    id: 5,
    name: 'Indie Man (500ml)',
    brand: 'Velhas Virgens',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-160809_973c5_sm.jpeg',
    price: 31.9,
  },
  {
    id: 6,
    name: 'Azzaca Lover (473ml)',
    brand: 'Dogma',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-1743877_8f62e_sm.jpeg',
    price: 39.9,
    // promo: 30.1,
  },
  {
    id: 7,
    name: 'Citra Brux (473ml)',
    brand: 'Dogma',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-2325726_4cf57_sm.jpeg',
    price: 39.9,
  },
  {
    id: 8,
    name: 'Apl Cidades (473ml)',
    brand: 'Perro Libre',
    url: 'https://untappd.akamaized.net/site/brewery_logos/brewery-134493_91c21.jpeg',
    price: 39.9,
  },
  {
    id: 9,
    name: 'American Pale Lager (473ml)',
    brand: 'Perro Libre',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-702546_d4c7a_sm.jpeg',
    price: 39.9,
  },
  {
    id: 10,
    name: 'Perro Libre IPA (473ml)',
    brand: 'Perro Libre',
    url: 'https://untappd.akamaized.net/site/brewery_logos/brewery-134493_91c21.jpeg',
    price: 39.9,
  },
  {
    id: 11,
    name: 'Hush (500ml)',
    brand: 'Hocus Pocus',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-1224719_126a7_sm.jpeg',
    price: 31.9,
  },
  {
    id: 12,
    name: 'APA Cadabra (500ml)',
    brand: 'Hocus Pocus',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-695612_95b6a_sm.jpeg',
    price: 31.9,
  },
  {
    id: 13,
    name: 'Double IPA Dedaleiro (500ml)',
    brand: 'Dama',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-31789_ba8cd_sm.jpeg',
    price: 39.9,
  },
  {
    id: 14,
    name: 'Dama Stout (600ml)',
    brand: 'Dama',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-653109_fc9ae_sm.jpeg',
    price: 31.9,
  },
  {
    id: 15,
    name: 'Lapa (500ml)',
    brand: '3 Cariocas',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-1549293_28c03_sm.jpeg',
    price: 31.9,
  },
  {
    id: 16,
    name: 'Sournilla (Passion Fruit) (500ml)',
    brand: '3 Cariocas',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-2325181_cbd62_sm.jpeg',
    price: 31.9,
  },
  {
    id: 17,
    name: 'Pilsen (500ml)',
    brand: 'Bierland',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-97003_950a4_sm.jpeg',
    price: 31.9,
  },
  {
    id: 18,
    name: 'Belgian Blond Ale (500ml)',
    brand: 'Bierland',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-1031538_ee292_sm.jpeg',
    price: 31.9,
  },
  {
    id: 19,
    name: 'Weizenbock',
    brand: 'Weihenstephaner',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-7408_a806b_sm.jpeg',
    price: 31.9,
  },
  {
    id: 20,
    name: 'Horny Pig (500ml)',
    brand: 'Blondine',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-947269_ae91c_sm.jpeg',
    price: 31.9,
  },
  {
    id: 21,
    name: 'Royal ESB (500ml)',
    brand: 'Blondine',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-1819821_5be1d_sm.jpeg',
    price: 31.9,
  },
  {
    id: 22,
    name: 'Feline (500ml)',
    brand: 'Blondine',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-1796521_408a4_sm.jpeg',
    price: 31.9,
  },
  {
    id: 23,
    name: 'Invicta Boss (500ml)',
    brand: 'Invicta',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-1006680_48046_sm.jpeg',
    price: 31.9,
  },
  {
    id: 24,
    name: 'El Xerife (473ml)',
    brand: 'Juan Caloto',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-2158240_8292e_sm.jpeg',
    price: 39.9,
  },
  {
    id: 25,
    name: 'Pipi e Flip (473ml)',
    brand: 'Juan Caloto',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-2471957_6921e_sm.jpeg',
    price: 39.9,
  },
  {
    id: 26,
    name: 'White Ale (473ml)',
    brand: 'Three Monkeys',
    url: 'https://untappd.akamaized.net/site/assets/images/temp/badge-beer-default.png',
    price: 39.9,
  },
  {
    id: 27,
    name: 'Dust Shock (473ml)',
    brand: 'Three Monkeys',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-2521721_6c8b5_sm.jpeg',
    price: 39.9,
  },
  {
    id: 28,
    name: 'Lohn Session IPA (500ml)',
    brand: 'Lohn',
    url: 'https://untappd.akamaized.net/site/beer_logos/beer-2352055_e3a81_sm.jpeg',
    price: 31.9,
  },
];
